// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHPoaDErJhAcxAz_8Qa0XxlsPLo-1LY0',
    appId: '1:804463426724:web:88d890e3d99f4d91913a31',
    messagingSenderId: '804463426724',
    projectId: 'myproject-flutter-one',
    authDomain: 'myproject-flutter-one.firebaseapp.com',
    storageBucket: 'myproject-flutter-one.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV54TsJNpXMWEVCvI48XCa-i_9_uiJnwQ',
    appId: '1:804463426724:android:12c8b0b1c1649af4913a31',
    messagingSenderId: '804463426724',
    projectId: 'myproject-flutter-one',
    storageBucket: 'myproject-flutter-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CUuev6HxWgR6mEPynkD3F1K7P313Cu4',
    appId: '1:804463426724:ios:e725127dddb4b326913a31',
    messagingSenderId: '804463426724',
    projectId: 'myproject-flutter-one',
    storageBucket: 'myproject-flutter-one.firebasestorage.app',
    iosBundleId: 'com.example.satuDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1CUuev6HxWgR6mEPynkD3F1K7P313Cu4',
    appId: '1:804463426724:ios:e725127dddb4b326913a31',
    messagingSenderId: '804463426724',
    projectId: 'myproject-flutter-one',
    storageBucket: 'myproject-flutter-one.firebasestorage.app',
    iosBundleId: 'com.example.satuDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLHPoaDErJhAcxAz_8Qa0XxlsPLo-1LY0',
    appId: '1:804463426724:web:993b62ead5421afe913a31',
    messagingSenderId: '804463426724',
    projectId: 'myproject-flutter-one',
    authDomain: 'myproject-flutter-one.firebaseapp.com',
    storageBucket: 'myproject-flutter-one.firebasestorage.app',
  );

}